server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # defalut 1000
      circuitBreaker:
        requestVolumeThreshold: 1 # defalut 20
        errorThresholdPrercentage: 50 # default 50

product:
  ribbon:
    listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
